/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { FlickArenaBet__factory } from "./FlickArenaBet__factory";
export { FlickArenaBetFactory__factory } from "./FlickArenaBetFactory__factory";
