/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export interface FlickArenaBetFactoryInterface extends utils.Interface {
  functions: {
    "createGame(uint256,uint256)": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "createGame"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "createGame",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "createGame", data: BytesLike): Result;

  events: {
    "GameCreated(address,address,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "GameCreated"): EventFragment;
}

export interface GameCreatedEventObject {
  gameAddress: string;
  host: string;
  targetScore: BigNumber;
  maxRounds: BigNumber;
}
export type GameCreatedEvent = TypedEvent<
  [string, string, BigNumber, BigNumber],
  GameCreatedEventObject
>;

export type GameCreatedEventFilter = TypedEventFilter<GameCreatedEvent>;

export interface FlickArenaBetFactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: FlickArenaBetFactoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    createGame(
      _targetScore: BigNumberish,
      _maxRounds: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;
  };

  createGame(
    _targetScore: BigNumberish,
    _maxRounds: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  callStatic: {
    createGame(
      _targetScore: BigNumberish,
      _maxRounds: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {
    "GameCreated(address,address,uint256,uint256)"(
      gameAddress?: null,
      host?: null,
      targetScore?: null,
      maxRounds?: null
    ): GameCreatedEventFilter;
    GameCreated(
      gameAddress?: null,
      host?: null,
      targetScore?: null,
      maxRounds?: null
    ): GameCreatedEventFilter;
  };

  estimateGas: {
    createGame(
      _targetScore: BigNumberish,
      _maxRounds: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    createGame(
      _targetScore: BigNumberish,
      _maxRounds: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;
  };
}
