/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { FlickArenaBet } from "./FlickArenaBet";
export type { FlickArenaBetFactory } from "./FlickArenaBetFactory";
export * as factories from "./factories";
export { FlickArenaBet__factory } from "./factories/FlickArenaBet__factory";
export { FlickArenaBetFactory__factory } from "./factories/FlickArenaBetFactory__factory";
